# Generated by Django 5.2.12 on 2026-03-09 08:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=240)),
                ("description", models.TextField()),
                ("event_date", models.DateField()),
                ("event_time", models.TimeField(blank=True, null=True)),
                ("location", models.CharField(max_length=200)),
                (
                    "location_url",
                    models.URLField(
                        blank=True,
                        default="",
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="events/"),
                ),
                ("is_public_attendees", models.BooleanField(default=True)),
                ("max_attendees", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "whatsapp_group_link",
                    models.URLField(
                        blank=True,
                        default="",
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https", "wa"]
                            )
                        ],
                    ),
                ),
                (
                    "gallery_link",
                    models.URLField(
                        blank=True,
                        default="",
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["event_date", "event_time"],
            },
        ),
        migrations.CreateModel(
            name="EventAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="attachments/")),
                ("filename", models.CharField(max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "icon",
                    models.CharField(
                        default="calendar",
                        help_text="Lucide icon name (https://lucide.dev)",
                        max_length=50,
                    ),
                ),
                ("color", models.CharField(default="#6366f1", max_length=7)),
            ],
            options={
                "verbose_name_plural": "Event Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("event_created", "New Event"),
                            ("event_updated", "Event Updated"),
                            ("rsvp", "New RSVP"),
                            ("reminder", "Event Reminder"),
                        ],
                        max_length=50,
                    ),
                ),
                ("message", models.TextField()),
                ("link", models.CharField(blank=True, default="", max_length=200)),
                (
                    "dedupe_key",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=120
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("going", "Going"),
                            ("maybe", "Maybe"),
                            ("not_going", "Can't Go"),
                        ],
                        default="going",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Waitlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
