# Generated by Django 6.0.3 on 2026-03-09 09:34

import events.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="eventattachment",
            name="file",
            field=models.FileField(upload_to=events.utils.attachment_upload_to),
        ),
    ]
